# Creating Numpy and Manipulating Arrays

In [2]:
import numpy as np

In [3]:
# There are several ways to create Numpy arrays:

b = np.array([[1, 2], [3, 4]])  # create a 2-dimensional array from a list of lists

c = np.zeros(8) # create an array of zeros

d = np.ones(8) # create an array of ones

In [4]:
# typecasting arrays
e = np.ones(5, dtype=int)
e

array([1, 1, 1, 1, 1])

In [5]:
# evenly spaced values
f = np.linspace(0,50, 100)
f

array([ 0.        ,  0.50505051,  1.01010101,  1.51515152,  2.02020202,
        2.52525253,  3.03030303,  3.53535354,  4.04040404,  4.54545455,
        5.05050505,  5.55555556,  6.06060606,  6.56565657,  7.07070707,
        7.57575758,  8.08080808,  8.58585859,  9.09090909,  9.5959596 ,
       10.1010101 , 10.60606061, 11.11111111, 11.61616162, 12.12121212,
       12.62626263, 13.13131313, 13.63636364, 14.14141414, 14.64646465,
       15.15151515, 15.65656566, 16.16161616, 16.66666667, 17.17171717,
       17.67676768, 18.18181818, 18.68686869, 19.19191919, 19.6969697 ,
       20.2020202 , 20.70707071, 21.21212121, 21.71717172, 22.22222222,
       22.72727273, 23.23232323, 23.73737374, 24.24242424, 24.74747475,
       25.25252525, 25.75757576, 26.26262626, 26.76767677, 27.27272727,
       27.77777778, 28.28282828, 28.78787879, 29.29292929, 29.7979798 ,
       30.3030303 , 30.80808081, 31.31313131, 31.81818182, 32.32323232,
       32.82828283, 33.33333333, 33.83838384, 34.34343434, 34.84

In [6]:
# 2 dimensional array with rand values
g = np.random.rand(4, 4)
g

array([[0.1665584 , 0.98471902, 0.05349209, 0.764292  ],
       [0.51168514, 0.70313663, 0.72542752, 0.68644819],
       [0.48097387, 0.13069659, 0.49698915, 0.34272655],
       [0.66812709, 0.27178557, 0.27342972, 0.92865592]])

In [7]:
h = np.array([1, 2, 3])  # create an array from a list

print(h)  # print the array
print(h[0])  # access the first element of the array
print(h[0:2])  # slice the first two elements of the array

[1 2 3]
1
[1 2]


# Manipulating Arrays

In [14]:
# You can use the "reshape" method to change the shape of a Numpy array without changing the data.

a = np.array([1, 2, 3, 4, 5, 6])
a.shape = (2, 3)
print(a)

[[1 2 3]
 [4 5 6]]


In [10]:
b = a.reshape(3, 2)  # reshape the array into a 3x2 matrix
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [11]:
c = a.reshape(2, 3)  # reshape the array into a 2x3 matrix
print(c)

[[1 2 3]
 [4 5 6]]


# Transposing Numpy arrays

In [15]:
# You can use the "T" attribute to transpose a Numpy array. This flips the array along its diagonal, so that rows become columns and vice versa.

d = b.T  # transpose the array
print(d)

[[1 3 5]
 [2 4 6]]
