# Basic Operations with Numpy Arrays

In [ ]:
# You can perform mathematical operations on Numpy arrays element-wise.

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a + b  # add the arrays element-wise
print(c)

d = a - b  # subtract the arrays element-wise
print(d)

e = a * b  # multiply the arrays element-wise
print(e)

f = a / b  # divide the arrays element-wise
print(f)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
