# Numpy array methods and functions 03

In [2]:
import numpy as np

In [3]:
# You can use Numpy's aggregate functions to perform operations across the entire array.

g = np.array([[1, 2], [3, 4]])

In [4]:
print(np.min(g))  # find the minimum value of the array

1


In [5]:
print(np.max(g))  # find the maximum value of the array

4


In [6]:
print(np.mean(g))  # calculate the mean of the array

2.5


In [7]:
print(np.median(g))  # calculate the median of the array

2.5


In [8]:
print(np.std(g))  # calculate the standard deviation of the array

1.118033988749895


In [9]:
print(np.sum(g))  # calculate the sum of the array

10


In [10]:
print(np.prod(g))  # calculate the product of the array

24


# Statistical functions

In [11]:
# You can use Numpy's statistical functions to calculate statistical measures of an array.

h = np.array([1, 2, 3, 4, 5])

print(np.corrcoef(h))  # calculate the correlation coefficient of the array

1.0
2.5


In [12]:
print(np.cov(h))  # calculate the covariance of the array

2.5


# Linear algebra functions

In [14]:
# Linear algebra functions

# You can use Numpy's linear algebra functions to perform operations such as matrix multiplication.

i = np.array([[1, 2], [3, 4]])

In [16]:
result = np.dot(i, i)
result

array([[ 7, 10],
       [15, 22]])

In [18]:
print(result)

[[ 7 10]
 [15 22]]


In [19]:
result = i @ i
result

array([[ 7, 10],
       [15, 22]])

In [20]:
print(result)

[[ 7 10]
 [15 22]]
